### ISSUE TITLE
"Put Back" not Available for Deleted Files in macOS Finder

### ISSUE THREAD

**Issue by fabb** [sindresorhus/trash-cli#19] opened 2018-09-22 14:33 UTC
When I delete files via Finder, then the deleted files in Trash have a helpful "Put Back" context menu entry. Files deleted via `trash` do not have this. It would be really nice if that was available as well.

**Comment by sindresorhus** [comment] 2018-09-22 14:38
Duplicate of #15

**Closed by sindresorhus** 2018-09-22 14:38 UTC
