### ISSUE TITLE
To alias or not to alias

### ISSUE THREAD

**Issue by galambalazs** [sindresorhus/trash-cli#8] opened 2016-02-22 12:21 UTC
Inside the README it says:
>  **Add alias** `rm=trash` to your .zshrc/.bashrc to reduce typing & safely trash files

But the in your rm is dangerous guide you wrote:

>  You **should no alias** rm to trash as it will break external scripts relying on the behavior of rm. Instead use it directly

https://github.com/sindresorhus/guides/blob/master/how-not-to-rm-yourself.md#safeguard-rm

One of them needs updating? :)

**Comment by sindresorhus** [comment] 2016-02-23 00:30
Duplicate of https://github.com/sindresorhus/trash-cli/issues/7.

**Closed by sindresorhus** 2016-02-23 00:30 UTC

**Comment by galambalazs** [comment] 2016-02-23 06:14
Haha wow, even the same title.

Soooory :)

**Comment by galambalazs** [comment] 2016-02-23 07:51
Will you also update the guide? 
https://github.com/sindresorhus/guides/blob/master/how-not-to-rm-yourself.md#safeguard-rm

**Comment by sindresorhus** [comment] 2016-02-23 07:53
Update it how?

**Comment by galambalazs** [comment] 2016-02-23 07:54
> You should **not** alias rm to trash as it will break external scripts relying on the behavior of rm. 

You said alias doesn't apply in scripts, so in the guide that sentence is not needed right?

**Comment by sindresorhus** [comment] 2016-02-23 07:56
Right. https://github.com/sindresorhus/guides/commit/f81249c0d5ced5dd4b0fca972aa1c300fe7044e3

**Comment by galambalazs** [comment] 2016-02-23 07:56
:+1:
