### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by Coaxial** [sindresorhus/trash-cli#2] opened 2015-10-18 17:01 UTC
Running node 0.12.7 on OS X 10.10.5:

```
$ npm i --global trash-cli
npm WARN engine trash-cli@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
/Users/hfp/.nvm/versions/node/v0.12.7/bin/trash -> /Users/hfp/.nvm/versions/node/v0.12.7/lib/node_modules/trash-cli/cli.js
trash-cli@1.1.0 /Users/hfp/.nvm/versions/node/v0.12.7/lib/node_modules/trash-cli
├── meow@3.4.2 (trim-newlines@1.0.0, object-assign@4.0.1, loud-rejection@1.0.0, camelcase-keys@1.0.0, minimist@1.2.0, redent@1.0.0, read-pkg-up@1.0.1, normalize-package-data@2.3.4)
├── update-notifier@0.5.0 (is-npm@1.0.0, chalk@1.1.1, string-length@1.0.1, repeating@1.1.3, semver-diff@2.0.0, configstore@1.2.1, latest-version@1.0.1)
└── trash@3.1.1 (escape-string-applescript@1.0.0, path-exists@2.0.0, pify@2.2.0, run-applescript@2.0.0, pinkie-promise@1.0.0, uuid@2.0.1, xdg-trashdir@2.0.0, fs-extra@0.24.0)

$ trash .bash_profile
/Users/hfp/.nvm/versions/node/v0.12.7/lib/node_modules/trash-cli/cli.js:4
const updateNotifier = require('update-notifier');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sindresorhus** [comment] 2015-10-18 17:11
Duplicate of #1.

**Closed by sindresorhus** 2015-10-18 17:11 UTC
