### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by albinekb** [sindresorhus/trash-cli#9] opened 2016-08-03 19:40 UTC
I tried to delete all my `node_modules` folders, but it seems like I hit some limit. Would it be possible to fix this by letting the trash-cli split up the expanded glob before performing the work?

> ❯ trash '**/node_modules'
> Error: spawn E2BIG
>     at exports._errnoException (util.js:1012:11)
>     at ChildProcess.spawn (internal/child_process.js:302:11)
>     at exports.spawn (child_process.js:372:9)
>     at exports.execFile (child_process.js:139:15)
>     at /usr/local/lib/node_modules/trash-cli/node_modules/pify/index.js:29:7
>     at /usr/local/lib/node_modules/trash-cli/node_modules/pify/index.js:12:10
>     at ret (/usr/local/lib/node_modules/trash-cli/node_modules/pify/index.js:56:34)
>     at module.exports (/usr/local/lib/node_modules/trash-cli/node_modules/trash/lib/osx.js:37:32)
>     at module.exports (/usr/local/lib/node_modules/trash-cli/node_modules/trash/index.js:22:45)
>     at Object.<anonymous> (/usr/local/lib/node_modules/trash-cli/cli.js:27:1)
> ~/Devel 1m 49s

**Comment by dawsonbotsford** [comment] 2017-01-27 09:14
You can see [here](https://github.com/sindresorhus/trash/blob/master/index.js#L4) that you are actually talking about a bug in [globby](https://github.com/sindresorhus/globby). You should report this issue there and close this.

**Comment by sindresorhus** [comment] 2017-01-27 11:05
@dawsonbotsford Uhm, no. The issue is that we send too many arguments (files) to the native trash binary.

**Comment by BenGitsCode** [comment] 2017-01-27 16:14
I think @sindresorhus  is correct here.  Why not just use `rm -rf '**/node_modules'` for that use instance? I mostly use this module for anytime I'm about to use `rm -rf` but I hang on the thought "will I ever need this again" and use `trash` just to be safe if I need to recover.

**Comment by sindresorhus** [comment] 2017-01-28 05:34
@BenGitsCode Yeah. I usually use [`del-cli`](https://github.com/sindresorhus/del-cli) for deleting `node_modules` as it's not something I would ever care about recovering.

**Comment by dawsonbotsford** [comment] 2017-01-28 06:18
It seems like directly calling a permanent delete function for path's which contain `node_modules` is reasonable. Then you would manually remove those paths from the list given to the native trash binary?

If this sounds right, I'd be happy to PR that functionality.

**Comment by sindresorhus** [comment] 2017-01-28 06:30
@dawsonbotsford No, that's not what I'm saying. That would be very surprising behavior. I just use `del-cli` instead of `trash` when deleting `node_modules`.

**Comment by sindresorhus** [comment] 2017-02-05 19:06
Pull request welcome :)

**Closed** 2021-01-27 11:38 UTC
Labels: enhancement, help wanted
